dist: trusty
group: edge
language: java
sudo: required
jdk: openjdk8

cache:
  directories:
  - $HOME/.m2

script:
- mvn clean install

after_success:
- mvn -DrepoToken=$COVERALLS_REPO_TOKEN cobertura:cobertura coveralls:report